#!/bin/bash

# 删除并重新创建目标目录
make_dirs() {
  local dir=$1
  if [ -d "$dir" ]; then
    rm -rf "$dir"  # 删除目录及其所有内容
  fi
  mkdir -p "$dir"  # 创建目录
}

# 创建目标目录
make_dirs "rule_script/Clash/China-Operator_IP"
make_dirs "rule_script/Surge/China-Operator_IP"
make_dirs "dns_script/Clash"

# 转换 IP 地址列表，生成 YAML 文件
make_yaml() {
  local input_file=$1
  local output_file="rule_script/Clash/China-Operator_IP/$2"
  local header=$3
  local cidr_type=$4

  echo "# ${header}" > "${output_file}"
  echo "payload:" >> "${output_file}"

  # 使用 xargs 代替 while read，提高处理速度
  cat "$input_file" | xargs -I {} echo "  - ${cidr_type},{}" >> "${output_file}"
}

# 转换 IP 地址列表，生成 LIST 文件
make_list() {
  local input_file=$1
  local output_file="rule_script/Surge/China-Operator_IP/$2"
  local header=$3
  local cidr_type=$4

  echo "# ${header}" > "${output_file}"

  # 使用 xargs 代替 while read，提高处理速度
  cat "$input_file" | xargs -I {} echo "${cidr_type},{}" >> "${output_file}"
}

# 转换 DNS Blocklist 列表，生成 DNS 规则
make_nameserver_policy() {
  local input_file=$1
  local output_file="dns_script/Clash/DNS-Blocklist.txt"
  local header=$2

  echo "# ${header}" >> "${output_file}"

  # 使用 xargs 代替 while read，跳过空行和注释行
  cat "$input_file" | grep -v '^#' | grep -v '^$' | xargs -I {} bash -c 'domain=$(echo {} | sed "s|^local=||"); echo "  $domain: rule-set:default-dns" >> "$0"; echo "  ++.$domain: rule-set:default-dns" >> "$0"' "$output_file"
}

# 转换 TikTok 广告域名列表
make_nameserver_policy native.tiktok.extended.txt "tiktok"
# 转换 Microsoft 域名列表
make_nameserver_policy native.winoffice.txt "Microsoft"
# 转换 Ads 域名列表
make_nameserver_policy popupads.txt "Ads"

# 其他 IP 列表转换
make_yaml cmcc.txt        cmcc4_No_Resolve.yaml       cmcc4   IP-CIDR
make_list cmcc.txt        cmcc4_No_Resolve.list       cmcc4   IP-CIDR
make_yaml cmcc6.txt       cmcc6_No_Resolve.yaml       cmcc6   IP-CIDR6
make_list cmcc6.txt       cmcc6_No_Resolve.list       cmcc6   IP-CIDR6
make_yaml unicom.txt      cucc4_No_Resolve.yaml       cucc4   IP-CIDR
make_list unicom.txt      cucc4_No_Resolve.list       cucc4   IP-CIDR
make_yaml unicom6.txt     cucc6_No_Resolve.yaml       cucc6   IP-CIDR6
make_list unicom6.txt     cucc6_No_Resolve.list       cucc6   IP-CIDR6
make_yaml chinanet.txt    ctcc4_No_Resolve.yaml       ctcc4   IP-CIDR
make_list chinanet.txt    ctcc4_No_Resolve.list       ctcc4   IP-CIDR
make_yaml chinanet6.txt   ctcc6_No_Resolve.yaml       ctcc6   IP-CIDR6
make_list chinanet6.txt   ctcc6_No_Resolve.list       ctcc6   IP-CIDR6
make_yaml cernet.txt      cernet4_No_Resolve.yaml     cernet4 IP-CIDR
make_list cernet.txt      cernet4_No_Resolve.list     cernet4 IP-CIDR
make_yaml cernet6.txt     cernet6_No_Resolve.yaml     cernet6 IP-CIDR6
make_list cernet6.txt     cernet6_No_Resolve.list     cernet6 IP-CIDR6
